default_language_version:
  python: python3
repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.11.9"
    hooks:
      - id: ruff
        args: ["--fix"]
        exclude: "docs"
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        exclude: "pdm.lock|examples/us_state_lookup.json"
        additional_dependencies:
          - tomli
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.15.0"
    hooks:
      - id: mypy
        exclude: "docs"
        additional_dependencies:
          [
            asyncpg,
            "anyio",
            asyncpg_stubs,
            pytest,
            time-machine,
            pytest-mock,
            pytest-timeout,
            "litestar",
            "types-click",
          ]
  - repo: https://github.com/sphinx-contrib/sphinx-lint
    rev: "v1.0.0"
    hooks:
      - id: sphinx-lint
